---
version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
