---
content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
formatter: "markdown table"
header-from: main.tf
output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}
    {{- printf "\n" -}}
settings:
  hide-empty: true
sort:
  enabled: true
  by: required
